---

- hosts: all
  remote_user: "{{ user }}"

  vars_files:
    - vars/main.yml

  roles:
    - name: essentials
      tags: essentials

    - name: timezone
      tags: timezone

    - name: iptables
      tags: iptables

    - name: fail2ban
      tags: fail2ban

    - name: kamaln7.swapfile
      tags: swapfile
      become: true

    - name: certbot
      tags: ssl

    - name: ssl
      tags: ssl

    - name: geerlingguy.nodejs
      tags: nodejs
      become: true

    - name: nginx
      tags: nginx
      become: true

    - name: php
      tags: php
      become: true

    - name: geerlingguy.composer
      tags: composer
      become: true

    - name: geerlingguy.mysql
      tags: mysql
      become: true

  tasks:
    - include: tasks/setup_deploy_folder_structure.yml
      tags: setup_deploy
