---

- name: Install php
  apt:
      pkg: "{{ item }}"
      state: installed
      update_cache: yes
  with_items:
    - php7.0-cli
    - php7.0-fpm
    - php7.0-curl
    - php7.0-gd
    - php7.0-intl
    - php7.0-mbstring
    - php7.0-mysql
    - php7.0-xml
    - php7.0-zip
  notify:
    - Start php-fpm
  become: true

- name: Add default resource pool
  template:
    src: "{{ item }}"
    dest: "/etc/php/7.0/fpm/pool.d/{{ item | basename | regex_replace('\\.j2','') }}"
    owner: root
    group: root
  with_fileglob:
    - "templates/*.j2"
  become: true
  notify: Restart php-fpm
